#!/usr/bin/env bash

realp=$(dirname "$(realpath "$0")")

# shellcheck source=./util.sh
. "${realp}/util.sh"

header BACKUP

cat <config | while read -r entry; do
	catch=$(catches "$entry")

	if ((catch)); then continue; fi

	dest=$(serialize "$entry")

	if [[ -d "$entry" ]]; then
		entry="${entry}/."
	fi

	cp -afv "$entry" "$dest"
done
