#!/usr/bin/env bash

header BACKUP

source "./util.sh"

mkdir ./data &>/dev/null

cat <config | while read -r entry; do
	fll "$(tput cols)" -

	if [[ -n $(catches "$entry") ]]; then
		continue
	fi

	dest=$(serialize "$entry")

	if [[ -d "$entry" ]]; then
		entry="${entry}/."
	fi

	echo -e "src: ${entry}\ndst: ${dest}"

	cp -afv "$entry" "$dest"
done
