#!/usr/bin/env bash

cat <<EOF
  #################
  ##  M.RESTORE  ##
  #################
EOF

source "./util.sh"

cat <config | while read -r entry; do
	echo
	# Comments
	if [[ "${entry:0:1}" == "#" ]]; then continue; fi
	# Empty
	if [[ -z $entry ]]; then continue; fi

	backup_entry="$(serialize "$entry")"

	if ! [[ -e $backup_entry ]]; then
		echo -e "$backup_entry doesnt exists. \n skipping ..."
		continue
	fi

	echo -e "d: ${backup_entry}\n${entry}"

	if [[ -f "$entry" ]]; then
		cp -f "$backup_entry" "$entry"
		continue
	fi

	# Directories
	if [[ -d "$entry" ]]; then
		cp -af "$backup_entry/." "$entry"
		continue
	fi
done
