#!/usr/bin/env bash

cat <<EOF
  #################
  ##  M.RESTORE  ##
  #################
EOF

source "./util.sh"

cat <config | while read -r entry; do
	echo
	# Comments
	if [[ "${entry:0:1}" == "#" ]]; then continue; fi
	# Empty
	if [[ -z $entry ]]; then continue; fi

	backup_entry="$(serialize "$entry")"

	if ! [[ -e $backup_entry ]]; then
		echo -e "$backup_entry doesnt exists. \n skipping ..."
		continue
	fi

	echo -e "d: ${backup_entry}\n${entry}"

	src="$backup_entry"

	if [[ -d "$entry" ]]; then
		src="${src}/."
	fi

	cp -af "$src" "$entry"
	continue
	# fi
done
