#!/usr/bin/env bash

header RSTORE

source "./util.sh"

cat <config | while read -r entry; do
	fll "$(tput cols)" -

	# Comments
	if [[ "${entry:0:1}" == "#" ]]; then continue; fi

	# Empty
	if [[ -z $entry ]]; then continue; fi

	backup_entry="$(serialize "$entry")"

	if ! [[ -e $backup_entry ]]; then
		echo -e "$backup_entry doesnt exists. \n skipping ..."
		continue
	fi

	echo -e "d: ${backup_entry}\n${entry}"

	src="$backup_entry"

	if [[ -d "$entry" ]]; then
		src="${src}/."
	fi

	cp -afv "$src" "$entry"
done
