#!/usr/bin/env bash

source "./util.sh"

header RSTORE

cat <config | while read -r entry; do
	backup_entry="$(serialize "$entry")"

	catch=$(catches "$backup_entry")

	if ((catch)); then continue; fi

	src="$backup_entry"

	if [[ -d "$entry" ]]; then
		src="${src}/."
	fi

	cp -afv "$src" "$entry"
done
