#!/usr/bin/env bash

realp=$(dirname "$(realpath "$0")")

# shellcheck source=./util.sh
. "${realp}/util.sh"

header RSTORE

cat <backup.conf | while read -r entry; do
	src="$(serialize "$entry")"

	catch=$(catches "$src")

	if ((catch)); then continue; fi

	if [[ -d "$entry" ]]; then
		src="${src}/."
	fi

	cp -afv "$src" "$entry"
done
